export const MUNICIPIOS_JALISCO = [
  "Acatic",
  "Acatlán de Juárez",
  "Ahualulco de Mercado",
  "Amacueca",
  "Amatitán",
  "Ameca",
  "Arandas",
  "Atengo",
  "Atenguillo",
  "Atotonilco el Alto",
  "Atoyac",
  "Autlán de Navarro",
  "Ayotlán",
  "Ayutla",
  "La Barca",
  "Bolaños",
  "Cabo Corrientes",
  "Cañadas de Obregón",
  "Casimiro Castillo",
  "Cihuatlán",
  "Zapotlán el Grande",
  "Cocula",
  "Colotlán",
  "Concepción de Buenos Aires",
  "Cuautitlán de García Barragán",
  "Cuautla",
  "Cuquío",
  "Chapala",
  "Chimaltitán",
  "Chiquilistlán",
  "Degollado",
  "Ejutla",
  "Encarnación de Díaz",
  "Etzatlán",
  "El Grullo",
  "Guachinango",
  "Guadalajara",
  "Hostotipaquillo",
  "Huejúcar",
  "Huejuquilla el Alto",
  "La Huerta",
  "Ixtlahuacán de los Membrillos",
  "Ixtlahuacán del Río",
  "Jalostotitlán",
  "Jamay",
  "Jesús María",
  "Jilotlán de los Dolores",
  "Jocotepec",
  "Juanacatlán",
  "Juchitlán",
  "Lagos de Moreno",
  "El Limón",
  "Magdalena",
  "Manalisco",
  "Mascota",
  "Mazamitla",
  "Mexticacán",
  "Mezquitic",
  "Mixtlán",
  "Ocotlán",
  "Ojuelos de Jalisco",
  "Pihuamo",
  "Poncitlán",
  "Puerto Vallarta",
  "Villa Purificación",
  "Quitupan",
  "El Salto",
  "San Cristóbal de la Barranca",
  "San Diego de Alejandra",
  "San Juan de los Lagos",
  "San Juanito de Escobedo",
  "San Marcos",
  "San Martín de Bolaños",
  "San Martín Hidalgo",
  "San Miguel el Alto",
  "Gómez Farías",
  "San Sebastián del Oeste",
  "Santa María de los Ángeles",
  "Sayula",
  "Tala",
  "Talpa de Allende",
  "Tamazula de Gordiano",
  "Tapalpa",
  "Tecalitlán",
  "Techalotlán",
  "Techaluta de Montenegro",
  "Tenamaxtlán",
  "Teocaltiche",
  "Teocuitatlán de Corona",
  "Tepatitlán de Morelos",
  "Tequila",
  "Teuchitlán",
  "Tizapán el Alto",
  "Tlajomulco de Zúñiga",
  "Tlaquepaque",
  "Tolimán",
  "Tomatlán",
  "Tonalá",
  "Tonaya",
  "Tonila",
  "Totatiche",
  "Tototlán",
  "Tuxcacuesco",
  "Tuxcueca",
  "Tuxpan",
  "Unión de San Antonio",
  "Unión de Tula",
  "Valle de Guadalupe",
  "Valle de Juárez",
  "San Gabriel",
  "Villa Corona",
  "Villa Guerrero",
  "Villa Hidalgo",
  "Yahualica de González Gallo",
  "Zacoalco de Torres",
  "Zapopan",
  "Zapotiltic",
  "Zapotitlán de Vadillo",
  "Zapotlán del Rey",
  "Zapotlanejo",
].sort((a, b) => a.localeCompare(b, "es"));