# Generated by Django 4.2.11 on 2026-03-22 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terrenos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terreno',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrenos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='terreno',
            index=models.Index(fields=['municipio'], name='terrenos_municip_340dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='terreno',
            index=models.Index(fields=['status'], name='terrenos_status_b267d8_idx'),
        ),
        migrations.AddIndex(
            model_name='terreno',
            index=models.Index(fields=['price'], name='terrenos_price_382189_idx'),
        ),
        migrations.AddIndex(
            model_name='terreno',
            index=models.Index(fields=['is_featured', '-created_at'], name='terrenos_is_feat_e222fc_idx'),
        ),
    ]
