# Generated by Django 4.2.20 on 2026-04-05 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terrenos', '0003_terreno_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='terrenos.terreno')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'terreno_favorites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'terreno')},
            },
        ),
    ]
