# Generated by Django 4.2.20 on 2026-04-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='terreno',
            name='nearby_services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='terreno',
            name='terrain_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
